GET {{baseUrl}}/api/skills?tamanho=10&pagina=2

###

GET {{baseUrl}}/api/skills/1

###

POST {{baseUrl}}/api/skills
Content-Type: application/json

{
    "name" : "MongoDB"
}

###

PUT {{baseUrl}}/api/skills/10
Content-Type: application/json

{
    "name" : "NOSQL"
}

###

DELETE {{baseUrl}}/api/skills/10
